name: Update NEXT ID

on:
  schedule:
    - cron: "0 0 */14 * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Update Discord Message
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          MESSAGE_ID: ${{ secrets.MESSAGE_ID }}

        run: |
          NOW=$(date +%s)

          TEASER=$((NOW + 86400))
          TRAILER=$((NOW + 259200))
          KIT=$((NOW + 432000))
          DROP=$((NOW + 604800))

          CONTENT="**NEXT ID**\n\nID Teaser -> Date in your timezone: <t:${TEASER}:F>\nID Trailer -> Date in your timezone: <t:${TRAILER}:F>\nID Kit -> Date in your timezone: <t:${KIT}:F>\nID Drop -> Date in your timezone: <t:${DROP}:F>\n\n**NOTICE:** Delays can and has happened, can go from 10 minutes to an hour."

          curl -X PATCH \
            -H "Authorization: Bot $BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"content\":\"$CONTENT\"}" \
            https://discord.com/api/v10/channels/$CHANNEL_ID/messages/$MESSAGE_ID
