name: Update Discord Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */14 * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Send updated schedule
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          NOW=$(date +%s)

          TEASER=$((NOW + 86400))
          TRAILER=$((NOW + 259200))
          KIT=$((NOW + 432000))
          DROP=$((NOW + 604800))

          curl -H "Content-Type: application/json" \
          -d "{
          \"content\":\"**NEXT ID**\n\nID Teaser → <t:${TEASER}:F>\nID Trailer → <t:${TRAILER}:F>\nID Kit → <t:${KIT}:F>\nID Drop → <t:${DROP}:F>\"
          }" \
          $WEBHOOK_URL
